<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ApuestaSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        $users = DB::table('users')->pluck('id', 'email');
        $juegos = DB::table('juegos')->pluck('id', 'nombre');

        $rows = [
            [
                'user_id' => $users['carlos@bookie20.test'],
                'juego_id' => $juegos['Ruleta'],
                'tipo' => 'ruleta',
                'descripcion' => 'Apuesta a color en ruleta',
                'seleccion' => 'Rojo',
                'resultado' => 'Negro',
                'monto' => 25.00,
                'cuota' => 2.00,
                'estado' => 'perdida',
                'fecha' => $now->copy()->subDays(13)->setTime(19, 15),
                'balance_antes' => 925.50,
                'balance_despues' => 900.50,
                'resuelta_at' => $now->copy()->subDays(13)->setTime(19, 16),
                'admin_id' => null,
            ],
            [
                'user_id' => $users['lucia@bookie20.test'],
                'juego_id' => $juegos['Ruleta'],
                'tipo' => 'ruleta',
                'descripcion' => 'Apuesta a color en ruleta',
                'seleccion' => 'Negro',
                'resultado' => 'Negro',
                'monto' => 80.00,
                'cuota' => 2.00,
                'estado' => 'ganada',
                'fecha' => $now->copy()->subDays(11)->setTime(21, 25),
                'balance_antes' => 1210.75,
                'balance_despues' => 1290.75,
                'resuelta_at' => $now->copy()->subDays(11)->setTime(21, 26),
                'admin_id' => null,
            ],
            [
                'user_id' => $users['mateo@bookie20.test'],
                'juego_id' => $juegos['Dados'],
                'tipo' => 'dados',
                'descripcion' => 'Apuesta a dado bajo o alto',
                'seleccion' => 'Alto (4-6)',
                'resultado' => 'Dado 2 - Bajo',
                'monto' => 10.00,
                'cuota' => 2.00,
                'estado' => 'perdida',
                'fecha' => $now->copy()->subDays(9)->setTime(17, 40),
                'balance_antes' => 585.00,
                'balance_despues' => 575.00,
                'resuelta_at' => $now->copy()->subDays(9)->setTime(17, 41),
                'admin_id' => null,
            ],
            [
                'user_id' => $users['sofia@bookie20.test'],
                'juego_id' => $juegos['Cara o Cruz'],
                'tipo' => 'cara_cruz',
                'descripcion' => 'Apuesta simple a cara o cruz',
                'seleccion' => 'Cara',
                'resultado' => 'Cara',
                'monto' => 50.00,
                'cuota' => 2.00,
                'estado' => 'ganada',
                'fecha' => $now->copy()->subDays(8)->setTime(18, 10),
                'balance_antes' => 3275.40,
                'balance_despues' => 3325.40,
                'resuelta_at' => $now->copy()->subDays(8)->setTime(18, 11),
                'admin_id' => null,
            ],
            [
                'user_id' => $users['daniel@bookie20.test'],
                'juego_id' => $juegos['Predicción'],
                'tipo' => 'prediccion',
                'descripcion' => 'Lloverá mañana antes de las 18:00',
                'seleccion' => 'Sí',
                'resultado' => null,
                'monto' => 45.50,
                'cuota' => 2.00,
                'estado' => 'pendiente',
                'fecha' => $now->copy()->subDays(4)->setTime(12, 5),
                'balance_antes' => 655.50,
                'balance_despues' => 610.00,
                'resuelta_at' => null,
                'admin_id' => null,
            ],
            [
                'user_id' => $users['valentina@bookie20.test'],
                'juego_id' => $juegos['Predicción'],
                'tipo' => 'prediccion',
                'descripcion' => 'El próximo mensaje del chat tendrá más de 20 caracteres',
                'seleccion' => 'Sí',
                'resultado' => 'Aceptada por administración',
                'monto' => 30.00,
                'cuota' => 2.00,
                'estado' => 'aceptada',
                'fecha' => $now->copy()->subDays(3)->setTime(10, 30),
                'balance_antes' => 780.25,
                'balance_despues' => 750.25,
                'resuelta_at' => null,
                'admin_id' => $users['admin@bookie20.test'],
            ],
            [
                'user_id' => $users['carlos@bookie20.test'],
                'juego_id' => $juegos['Predicción'],
                'tipo' => 'prediccion',
                'descripcion' => 'El usuario Carlos ganará su siguiente giro de ruleta',
                'seleccion' => 'Sí',
                'resultado' => 'Predicción no cumplida',
                'monto' => 15.00,
                'cuota' => 2.00,
                'estado' => 'perdida',
                'fecha' => $now->copy()->subDays(2)->setTime(20, 0),
                'balance_antes' => 915.50,
                'balance_despues' => 900.50,
                'resuelta_at' => $now->copy()->subDay()->setTime(12, 0),
                'admin_id' => $users['admin@bookie20.test'],
            ],
            [
                'user_id' => $users['lucia@bookie20.test'],
                'juego_id' => $juegos['Predicción'],
                'tipo' => 'prediccion',
                'descripcion' => 'La ruleta sacará verde durante la sesión especial',
                'seleccion' => 'Sí',
                'resultado' => 'Predicción cumplida',
                'monto' => 25.00,
                'cuota' => 2.00,
                'estado' => 'ganada',
                'fecha' => $now->copy()->subDay()->setTime(16, 20),
                'balance_antes' => 1240.75,
                'balance_despues' => 1290.75,
                'resuelta_at' => $now->copy()->subHours(8),
                'admin_id' => $users['admin@bookie20.test'],
            ],
            [
                'user_id' => $users['operador@bookie20.test'],
                'juego_id' => $juegos['Dados'],
                'tipo' => 'dados',
                'descripcion' => 'Apuesta a dado bajo o alto',
                'seleccion' => 'Bajo (1-3)',
                'resultado' => 'Dado 1 - Bajo',
                'monto' => 40.00,
                'cuota' => 2.00,
                'estado' => 'ganada',
                'fecha' => $now->copy()->subHours(12),
                'balance_antes' => 7960.00,
                'balance_despues' => 8000.00,
                'resuelta_at' => $now->copy()->subHours(12)->addMinute(),
                'admin_id' => null,
            ],
            [
                'user_id' => $users['daniel@bookie20.test'],
                'juego_id' => $juegos['Cara o Cruz'],
                'tipo' => 'cara_cruz',
                'descripcion' => 'Apuesta simple a cara o cruz',
                'seleccion' => 'Cruz',
                'resultado' => 'Cara',
                'monto' => 20.00,
                'cuota' => 2.00,
                'estado' => 'perdida',
                'fecha' => $now->copy()->subHours(5),
                'balance_antes' => 630.00,
                'balance_despues' => 610.00,
                'resuelta_at' => $now->copy()->subHours(5)->addMinute(),
                'admin_id' => null,
            ],
        ];

        DB::table('apuestas')->insert(array_map(function (array $row) use ($now) {
            return array_merge($row, [
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }, $rows));
    }
}
